name: CI

on:
  push:

jobs:
  release:
    name: Linux
    runs-on: ${{ matrix.os }}
    # create a build matrix for jobs
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use node
        uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: install dependency
        run: npm i
      - name: build
        run: npm run build && ls build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BT_TOKEN: ${{ secrets.BT_TOKEN }}
