name: CI

on:
  push:

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use node
        uses: actions/setup-node@v3
        with:
          node-version: 12
          cache: 'npm'
      - name: install dependency
        run: npm i
      - name: build
        run: npm run build && ls build
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
           files: build/k 0.4.1.AppImage
